### ISSUE TITLE
Syntax error with server config

### ISSUE THREAD

**Issue by jordantrizz** [cemathey/hll_seed_vip#8]
Getting the following error

```
Traceback (most recent call last):
  File "/code/hll_seed_vip/cli.py", line 276, in <module>
    trio.run(main)
  File "/root/.cache/pypoetry/virtualenvs/hll-seed-vip-MATOk_fk-py3.11/lib/python3.11/site-packages/trio/_core/_run.py", line 2262, in run
    raise runner.main_task_outcome.error
  File "/code/hll_seed_vip/cli.py", line 43, in main
    config = load_config(Path(CONFIG_DIR).joinpath(CONFIG_FILE_NAME))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/hll_seed_vip/utils.py", line 39, in load_config
    return ServerConfig(
           ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hll-seed-vip-MATOk_fk-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ServerConfig
discord_webhooks.0
  URL input should be a string or URL [type=url_type, input_value={'url': 'https://discord....'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/url_type
```

Most likely due to docker-compose.yml not using variables for config and log file volume definitions.

**Comment by cemathey** [comment]
Are you running this inside Docker? I need more info, it includes defaults and makes the directory if it doesn't exist, your stack trace is cut off so I can't see the actual error.

**Comment by jordantrizz** [comment]
I updated the trace. I figured it out and put in a pull request.
